.TH GetDP 1 "8 July 2013" "2.4" "GetDP Manual Pages"
.UC 4
.\" ********************************************************************
.SH NAME
GetDP \- a General environment for the treatment of Discrete Problems
.\" ********************************************************************
.SH SYNOPSIS
.B getdp [file] [options]
.\" ********************************************************************
.SH DESCRIPTION
\fIGetDP\fP is a general finite element solver using mixed elements to
discretize de Rham-type complexes in one, two and three
dimensions. The main feature of \fIGetDP\fP is the closeness between
the input data defining discrete problems (written by the user in
ASCII data files) and the symbolic mathematical expressions of these
problems.
.PP
\fIGetDP\fP is a command-line program. See \fIGmsh\fP for a graphical
front-end.
.\" ********************************************************************
.SH WARNING
This man page does not describe the syntax of the input files: you
should refer to the info documentation for this (e.g. with \fBinfo
getdp\fP). Up-to-date versions of the manual in various formats are
available at \fIhttp://www.geuz.org/getdp/\fP.
.\" ********************************************************************
.SH PROCESSING OPTIONS
.TP 4
.B file
is an ASCII file containing the problem definition, i.e., the
structures the Texinfo documentation will teach you to create. This
file can include other files, so that only one problem definition file
should always be given on the command line. The input files containing
the problem definition structure are usually given the \fI.pro\fP
extension (if so, there is no need to specify the extension on the
command line). The name of this file (without the extension) is used
as a basis for the creation of intermediate files during the
pre-processing and the processing stages.
.TP 4
.B \-pre \fIresolution-id\fP
performs the pre-processing associated with the resolution called
\fIresolution-id\fP. In the pre-processing stage, \fIGetDP\fP creates
the geometric database (from the mesh file), identifies the degrees of
freedom (the unknowns) of the problem and sets up the constraints on
these degrees of freedom. The pre-processing creates a file with 
a \fI.pre\fP extension. If \fIresolution-id\fP is omitted, the list of
available choices is displayed.
.TP 4
.B \-cal
performs the processing. This requires that a pre-processing has been
performed previously, or that a \fB\-pre\fP option is given on the
same command line. The performed resolution is the one given as an
argument to the \fB\-pre\fP option. In the processing stage,
\fIGetDP\fP executes all the operations of the selected resolution
(such as matrix assemblies, system resolutions, ...). The processing
creates a file with a \fI.res\fP extension.
.TP 4
.B \-pos \fIpost-operation-id\fP(s)
performs the post-processing operations selected by the 
\fIpost-operation-id\fP(s). This requires that a processing has been
performed previously, or that a \fB\-cal\fP option is given on the
same command line. If \fIpost-operation-id\fP is omitted, the list of
available choices is displayed.
.TP 4
.B \-msh \fIfilename\fP
reads the mesh database from \fIfilename\fP rather than reading it
from the default problem file name with the \fI.msh\fP extension
appended.
.TP 4
.B \-restart
resumes time loop processing from where it stopped.
.TP 4
.B \-solve \fIresolution-id\fP
same as \-pre \fIresolution-id\fP \-cal.
.TP 4
.B \-split
saves processing results in separate files (one for each timestep).
.TP 4
.B \-res \fIfilename\fP(s)
loads processing results from \fIfilename(s)\fP instead of from the
default problem file name with the \fI.res\fP extension appended.
.TP 4
.B \-name \fIstring\fP
uses \fIstring\fP as the default generic file name for input or output
of mesh, pre-processing and processing files.
.TP 4
.B \-adapt \fIfilename\fP(s)
reads adaptation constraints from \fIfilename(s)\fP.
.TP 4
.B \-order \fIfloat\fP
specifies maximum interpolation order.
.\" ********************************************************************
.SH LINEAR SOLVER OPTIONS
.TP 4
.B \-solver \fIfilename\fP
specifies solver parameter file.
.TP 4
.B [PETSc options]
PETSc options (if GetDP was compiled with PETSc support).
.\" ********************************************************************
.SH LINEAR SOLVER OPTIONS
.TP 4
.B \-bin
creates binary output files.
.B \-v2
creates mesh-based Gmsh output files when possible
.\" ********************************************************************
.SH OTHER OPTIONS
.TP 4
.B \-check
lets you check the problem structure interactively.
.TP 4
.B \-v \fIint\fP
sets the verbosity level. A value of 0 means that no information will
be displayed during processing. Higher values increase the amount of
information displayed.
.TP 4
.B \-p \fIint\fP
sets the progress update rate. This controls the refreshment rate of
the counter indicating the progress of the current computation.
.TP 4
.B \-onelab \fIname\fP \fIaddress\fP
communicates with OneLab server through socket.
.TP 4
.B \-version
displays the version number.
.TP 4
.B \-info
displays detailed version information.
.TP 4
.B \-help
displays a message listing basic usage and available options.
.PP
.\" ********************************************************************
.SH AUTHORS
Patrick Dular (patrick.dular at ulg.ac.be) and Christophe Geuzaine
(cgeuzaine at ulg.ac.be). See the documentation for a comprehensive
list of contributors.
.\" ********************************************************************
.SH SEE ALSO
.BR gmsh (1),
.BR
GetDP examples (\fI/usr/share/doc/getdp-*/\fR),
.BR
GetDP homepage (\fIhttp://www.geuz.org/getdp/\fR).
.PP
The full documentation for GetDP is maintained as a Texinfo manual.
If the
.B info
and
.B getdp
programs are properly installed at your site, the command
.IP
.B info getdp
.PP
should give you access to the complete manual.
